name: Docker publish to docker hub

on:
  release:
    types:
      - published

jobs:
  docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:        
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: tinomeister/shtapigateway

      - name: Create .env file
        run: |
          echo "USERS_SERVICE="${{ secrets.USERS_SERVICE }}"" >> .env
          echo "HUBS_SERVICE="${{ secrets.HUBS_SERVICE }}"" >> .env
          echo "EXTERNAL_SERVICE="${{ secrets.EXTERNAL_SERVICE }}"" >> .env
        shell: bash
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
